config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :playlists

resources :songs do
 
  collection do
   	get 'listofsong'
	get "/listening/:id" => "songs#listening"
	get "/listenin/:id" => "songs#listenin"
	get "/pop/:id" => "songs#pop"
  end
   
end

  resources :comments
  resources :moods

  resources :playlists
  resources :raters do
collection do
get "/signup" => "raters#signup"
get "/up/:id" => "raters#up"
get "/upp/:id" => "raters#upp"
get "/uppp/:id" => "raters#uppp"
end
end

  resources :populars

  resources :artists
  get "/search" => "songs#search", as: 'search'
  match '/lyrics', to: 'moods#lyrics', via: :get
match '/lyricsdetected', to: 'moods#lyricsdetected', via: :post
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users

end

app/models/artist.rb
class Artist < ActiveRecord::Base
belongs_to :song
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/mood.rb
class Mood < ActiveRecord::Base
belongs_to :song
has_many :rater
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :mood
  belongs_to :user
  has_many :songs
end

app/models/popular.rb
class Popular < ActiveRecord::Base
  belongs_to :song
end

app/models/rater.rb
class Rater < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
  belongs_to :mood
validates_uniqueness_of :user_id, scope: :song_id
end

app/models/reccommender.rb
class Reccommender < ActiveRecord::Base
  belongs_to :rater
	validates_uniqueness_of :user_id
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :mood
  belongs_to :artist
has_attached_file :audio                   
validates_attachment_presence :audio
validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
  	if User.count == 1
    	self.role ||= :admin
    else
    	self.role ||= :user
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/moods_controller.rb
class MoodsController < ApplicationController
  before_action :set_mood, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @moods = Mood.all
    respond_with(@moods)
  end

  def show
    respond_with(@mood)
  end

  def new
    @mood = Mood.new
    respond_with(@mood)
  end
	
  def lyricsdetected
	
	 file = params[:uploaded_file].read
	File.open('word.txt', 'w') do |f2|    
  		f2.puts file 
		end
	  
	`python def.py`
	
end
  def lyrics

 end
  def edit
  end

  def create
    @mood = Mood.new(mood_params)
    @mood.save
    respond_with(@mood)
  end

  def update
    @mood.update(mood_params)
    respond_with(@mood)
  end

  def destroy
    @mood.destroy
    respond_with(@mood)
  end

  private
    def set_mood
      @mood = Mood.find(params[:id])
    end

    def mood_params
      params.require(:mood).permit(:moodname)
    end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  before_action :set_song, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @songs = Song.all
    respond_with(@songs)
  end

  def search


@moods=Mood.all
@raters=Rater.where(mood_id: params[:mood] ,:user_id => current_user.id, :play => 1)
recomotheruser=Rater.where("mood_id=? and user_id<> ?",params[:mood],current_user.id)

recomuser=Rater.where("mood_id<>? and user_id=?",params[:mood],current_user.id)

groupedset=recomotheruser.where("song_id IN (select song_id from raters where mood_id=? and user_id=?)",params[:mood],current_user.id)

f1=groupedset.select("user_id,mood_id,song_id,count(*) as total_count").group(:user_id).order("total_count DESC").first

u=Reccommender.where(user_id: current_user.id).take

unless f1.nil?
if f1.mood_id == 1
u.update( happy: f1.user_id )
elsif f1.mood_id ==2
u.update( sad: f1.user_id )
elsif f1.mood_id ==3
u.update( angry: f1.user_id )
elsif f1.mood_id ==4
u.update( fear: f1.user_id )
elsif f1.mood_id ==5
u.update( surprise: f1.user_id )
end
u.save
end



# recommended for searched songs

f22=groupedset.select("user_id,mood_id,song_id,count(*) as total_count").group(:user_id).order("total_count DESC").limit(5)

r=Rater.where(user_id=0)
f22.each do |u|
	recc=recomuser.where("song_id IN (select song_id from raters where mood_id=? and user_id=?)", params[:mood],u.user_id)
		r=r|recc
end

   raters=Rater.where(:mood_id=>params[:mood] , :user_id => current_user.id, :play => 1)
   popu=Rater.where("song_id IN (select song_id from populars order by count desc limit 20) and user_id=? and mood_id <> ? ",current_user.id, params[:mood])

popoose=popu.where("count = 0 or search = 0 and user_id=? and mood_id <> ? ",current_user.id, params[:mood]).take(5)
popu=popu.take(10)
@rec = r|popu|popoose



  end


  def show
	Popular.create(song_id: params[:id], count: 0)
  @text = File.read("word.txt") do  |f| 
     f.each_line do  |line| 
      @text = @text.to_s + '<br>'+line.to_s 
      end 
    end
puts @text
    respond_with(@song)

  end

  def new
    @song = Song.new
    respond_with(@song)
  end

  def edit
  end

	def listening
	@rater=Rater.find(params[:id])
	@rater.count=@rater.count+1
	@rater.save
	render :text => 'Done' 
	end


	def pop
	@popular=Popular.where(:song_id => params[:id]).take
	@popular.count=@popular.count+1
	@popular.save
	render :text => 'Done' 
	end


	def listenin
	@rater=Rater.find(params[:id])
	@rater.search=@rater.search+1
	@rater.save
	render :text => 'Done' 
	end


def listofsong
@moods=Mood.all
@raters=Rater.where(:user_id => current_user.id)
  end



  def create
    @song = Song.new(song_params)
   songname = @song.name
    artistname = @song.artist.artistname
     #tatementa = params[:song][:artistname]
     st1=artistname.gsub(" ","_")
     
    #tatementt =params[:song][:songname]
     st2=songname.gsub(" ","_")
    
    `python3 crawl.py #{st1} #{st2}`
 
   `python def.py`
      file = File.open("result.txt", 'rb')                           
	while !file.eof?
		line1 = file.readline
                
		#line1=line.gsub(/\n/," ")
	end
   
    
    @song.mood_id=line1
    @song.save
    respond_with(@song)
  end

  def update
    @song.update(song_params)
    respond_with(@song)
  end

  def destroy
	Popular.where(song_id: @song.id).delete
    @song.destroy
    respond_with(@song)
  end

  private
    def set_song
      @song = Song.find(params[:id])
    end

    def song_params
      params.require(:song).permit(:name, :mood_id, :artist_id, :audio)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :authenticate_user!
  after_action :verify_authorized

  def index
    @users = User.all

    # authorize current_user
  end

  def show
    @user = User.find(params[:id])
    # authorize @user
  end

  def update
    @user = User.find(params[:id])
    authorize @user
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    # authorize user
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mood_helper.rb
module MoodHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/popular_helper.rb
module PopularHelper
end

app/helpers/rater_helper.rb
module RaterHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/moods/_form.html.erb
<%= simple_form_for(@mood) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :moodname %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/moods/edit.html.erb
<h1>Editing Mood</h1>

<%= render 'form' %>

<%= link_to 'Show', @mood %> |
<%= link_to 'Back', moods_path %>

app/views/moods/index.html.erb
<html>

<head>
<style>
table, th, td {
    border: 5px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
table#t01 {
    width: 100%;    
    background-color: #f1f1c1;
}
</style>
</head>


<p id="notice"><%= notice %></p>

<h1>Listing Moods</h1>

<table id="t01" border=2 style="width:100%">
  <thead>
    <tr>
	<th>Mood ID </th>
      <th>Moodname</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moods.each do |mood| %>
      <tr>
        <td><%= mood.id %></td>
        <td><%= mood.moodname %></td>
        <td><%= link_to 'Show', mood %></td>
        <td><%= link_to 'Edit', edit_mood_path(mood) %></td>
        <td><%= link_to 'Destroy', mood, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Mood', new_mood_path %>

app/views/moods/lyrics.html.erb
<%= form_tag(lyricsdetected_path, {:multipart=>true, :method => :post}) do %>  

  <p>
      <%= label_tag :uploaded_file, 'Upload your file.' %><br />
      <%= file_field_tag :uploaded_file %>
  </p>
  <p><%= submit_tag 'upload' %></p>

<%- end -%>

app/views/moods/lyricsdetected.html.erb
<h1> MOOD DETECTED: </h1>
<pre>
<%= render :file => 'result.txt' %>
<%= render :file => 'word.txt' %>
</pre>

<%= link_to 'More Lyrics Detection',lyrics_path %> |

<%= link_to 'Home Page',listofsong_songs_path %>

app/views/moods/new.html.erb
<h1>New Mood</h1>

<%= render 'form' %>

<%= link_to 'Back', moods_path %>

app/views/moods/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Moodname:</strong>
  <%= @mood.moodname %>
</p>

<%= link_to 'Edit', edit_mood_path(@mood) %> |
<%= link_to 'New Mood', new_mood_path %> |
<%= link_to 'Back', moods_path %>

app/views/songs/_form.html.erb
<%= simple_form_for(@song) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name %>

    <%= f.association :artist, :label_method => :artistname , :value_method => :id %>
    <%= f.file_field :audio %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

<%= link_to 'CHECK LYRICS MOOD FIRST?', lyrics_path %>

app/views/songs/edit.html.erb
<h1>Editing Song</h1>

<%= render 'form' %>

<%= link_to 'Show', @song %> |
<%= link_to 'Back', songs_path %>

app/views/songs/index.html.erb
<html>

<head>
<style>
table, th, td {
    border: 5px solid black;
    border-collapse: collapse;
}
th, td {
    padding: 5px;
    text-align: left;
}
table#t01 {
    width: 100%;    
    background-color: #f1f1c1;
}
</style>
</head>


<p id="notice"><%= notice %></p>

<h1>Listing Songs</h1>

<table id="t01" border=2 style="width:100%">


  <thead>
    <tr>
      <th>Song Id </th>
      <th>Name</th>
      <th>Mood</th>
      <th>Artist</th>
      <th colspan="5"></th>
    </tr>
  </thead>

  <tbody>
    <% @songs.each do |song| %>
      <tr>
	<td><%= song.id %></td>
        <td><%= song.name %></td>
        <td><%= song.mood.moodname %></td>
        <td><%= song.artist.artistname %></td>
	<td><a href='<%= song.audio.url %>'>Play</a> </td>
        <td><%= link_to 'Show', song %></td>
        <td><%= link_to 'Edit', edit_song_path(song) %></td>
        <td><%= link_to 'Destroy', song, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Song', new_song_path %>

app/views/songs/listofsong.html.erb
<!DOCTYPE html>

<html lang="en">
<head>
<!-- add styles and scripts  -->
	<%=stylesheet_link_tag 'css/styles.css' %>

	<%=stylesheet_link_tag 'stars.css' %>
	<%#stylesheet_link_tag 'me.css' %>
	<%=javascript_include_tag 'js/jquery-1.7.2.min.js' ,'js/jquery-ui-1.8.21.custom.min.js','js/man.js' %>
	<%=javascript_include_tag 'sorttable.js'%>
	<br><br>
<h3> SEARCH SONGS BASED ON MOOD </h3>
<form action="/search">
	<select class="form-control" name="mood">
		<% @moods.each do |m| %>
		  <option value="<%= m.id %>"><%= m.moodname.titleize %></option>
		<% end %>
	</select>
	<input type="submit" class="btn btn-primary">
</form>

<br>
<p> Click here to download the MP3 Player for Offline Purposes! :) </p>
<a href="<%= image_path("OfflinePurpleBlues.zip")%>" download>Offline Purple Blues</a>
<%= link_to '★' ,raters_path%>
<br><br><br><br><br>
<script>
function myFunction(id) {
    var lTable = document.getElementById(id);
    lTable.style.display = (lTable.style.display == "table") ? "none" : "table";
}

function Rateme(number)
{
$.ajax('/raters/up/'+number,{type: 'GET'});
}
function Rateme1(number)
{
$.ajax('/raters/upp/'+number,{type: 'GET'});
}
function Rateme2(number)
{
$.ajax('/raters/uppp/'+number,{type: 'GET'});
}
</script>
    
</head>
<body>
<h3> PLAYING ALL SONGS </h3>

    <div class="example">

        <div class="player">
            <div class="pl"></div>
            <div class="title"></div>

	    <div class="mood"></div>
            <div class="cover"></div>
            <div class="controls">
                <div class="play"></div>
                <div class="pause"></div>
                <div class="rew"></div>
                <div class="fwd"></div>
            </div>
            <div class="volume"></div>
            <div class="tracker"></div>
        </div>

        <ul class="playlist">
	<% raters=@raters.where(:play => 1).order(count: :desc,search: :desc).take(10) %>
	 <% raters.each do |ra| %>
            <li audiourl="<%=ra.song.audio.url%>" artist="<%=ra.song.artist.artistname%>" mood="<%=ra.mood.moodname%>" songid="<%=ra.song.id%>" rateid="<%=ra.id%>" ><%=ra.song.name%> </li>
	  <% end %>        
	</ul>

    </div>
</body>

<a href="#" onclick="myFunction('t01'); return false;">Click here to rate/download</a>

<table class="sortable" id="t01" border=2 style="width:100%">
<h1> DOWNLOAD SONGS! </h1>
<p> Click Control+S on the audio player page, if the file does not get downloaded. </p>
<h1> RATE SONGS! </h1>
<p> 3 stars => perfect. 2 stars => change mood. 1 Star => Wrong mood wrong song!</p>

<br><br>

  <thead>
    <tr>
      <th>Name</th>
      <th>Mood</th>
      <th>Artist</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>

   <% @raters.each_with_index do |ra,i| %>

      <tr>
        <td><%= ra.song.name %></td>
        <td><%= ra.mood.moodname %></td>
        <td><%= ra.song.artist.artistname %></td>
        <td><a href="<%=ra.song.audio.url(:original, false)%>" download>Download</a></td>
 <td><span class="rating" id="<%= i %>">
        
        <input type="radio" onclick="Rateme2(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-3" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-3" class="rating-star"></label>
        <input type="radio" onclick="Rateme(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-2" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-2" class="rating-star"></label>
        <input type="radio" onclick="Rateme1(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-1" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-1" class="rating-star"></label>
</span></td> 
      </tr>
    <% end %>
  </tbody>
</table>
<br><br>


</html>

app/views/songs/new.html.erb
<h1>New Song</h1>

<%= render 'form' %>

<%= link_to 'Back', songs_path %>

app/views/songs/search.html.erb
<head>

	<%=stylesheet_link_tag 'css/styles.css' %>
	<%=stylesheet_link_tag 'stars.css' %>
	<%=stylesheet_link_tag 'me.css' %>
	<%=javascript_include_tag 'js/jquery-1.7.2.min.js' ,'js/jquery-ui-1.8.21.custom.min.js','js/man1.js' %>
	<%=javascript_include_tag 'sorttable.js'%>

</head>
<script>
function Rateme(number)
{
$.ajax('/raters/up/'+number,{type: 'GET'});
}

function Rateme2(number)
{
$.ajax('/raters/uppp/'+number,{type: 'GET'});
}

function Rateme1(number)
{
$.ajax('/raters/upp/'+number,{type: 'GET'});
}
</script>
<body>
<h3> SEARCH SONGS BASED ON MOOD </h3>
<form action="/search">
	<select class="form-control" name="mood">
		<% @moods.each do |m| %>
		  <option value="<%= m.id %>"><%= m.moodname.titleize %></option>
		<% end %>
	</select>
	<input type="submit" class="btn btn-primary">
</form>

<h3> PLAYING ALL SONGS </h3>

 <div class="example">

        <div class="player">
            <div class="pl"></div>
            <div class="title"></div>
            <div class="artist"></div>
	    <div class="mood"></div>
            <div class="cover"></div>
            <div class="controls">
                <div class="play"></div>
                <div class="pause"></div>
                <div class="rew"></div>
                <div class="fwd"></div>
            </div>
            <div class="volume"></div>
            <div class="tracker"></div>
        </div>

   


        <ul class="playlist">
	  <% @raters.each do |ra| %>
            <li audiourl="<%=ra.song.audio.url%>" artist="<%=ra.song.artist.artistname%>" mood="<%=ra.mood.moodname%>" rateid="<%=ra.id%>" songid="<%=ra.song.id%>" ><%=ra.song.name%> </li>
	  <% end %>        
	</ul>

    </div>
</body>




<br><br>
<br><br>
<%= link_to '★' ,raters_path%>
<h1>Listing ALL Songs based on MOOD SEARCHED</h1>
<table class="table table-hover">
 <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Mood</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
<%i=0%>
   <% @raters.each do |ra| %>
<% i+=1%>
      <tr>
        <td><%= ra.song.name %></td>
        <td><%= ra.song.artist.artistname %></td>
	<td><%= ra.mood.moodname %></td>
        <td><a href="<%=ra.song.audio.url(:original, false)%>" download>Download</a></td>
 <td><span class="rating" id="<%= i %>">
        
        <input type="radio" onclick="Rateme2(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-3" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-3" class="rating-star"></label>
<% i+=1%>
        <input type="radio" onclick="Rateme(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-2" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-2" class="rating-star"></label>
<% i+=1%>
        <input type="radio" onclick="Rateme1(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-1" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-1" class="rating-star"></label>
</span></td> 
      </tr>
    <% end %>
  </tbody>
</table>


<h1>RECOMMENDED SONGS: </h1>
<table class="table table-hover">
 <thead>
    <tr>
      <th>Name</th>
      <th>Artist</th>
      <th>Mood</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
   <% @rec.each do |ra| %>
<% i+=1%>

      <tr>
        <td><%= ra.song.name %></td>
        <td><%= ra.song.artist.artistname %></td>
	<td><%= ra.mood.moodname %></td>
        <td><a href="<%=ra.song.audio.url(:original, false)%>" download>Download</a></td>
 <td><span class="rating" id="<%= i %>">
        
        <input type="radio" onclick="Rateme2(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-3" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-3" class="rating-star"></label>
<% i+=1%>
        <input type="radio" onclick="Rateme(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-2" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-2" class="rating-star"></label>
<% i+=1%>
        <input type="radio" onclick="Rateme1(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-1" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-1" class="rating-star"></label>
</span></td> 
      </tr>
    <% end %>
  </tbody>
</table>

</html>

app/views/songs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>ID:</strong>
  <%= @song.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @song.name %>
</p>

<p>
  <strong>Mood:</strong>
  <%= @song.mood.moodname %>
</p>

<p>
  <strong>Artist:</strong>
  <%= @song.artist.artistname %>
</p>

<pre>
<%=@text%>

</pre>
<%= @song.audio_file_name %>
<a href='<%= @song.audio.url %>'>Song</a>|

<%= link_to 'Edit', edit_song_path(@song) %> |
<%= link_to 'Back', songs_path %> |  <%= link_to 'New Song', new_song_path %>