config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :playlists

resources :songs do
 
  collection do
   	get 'listofsong'
	get "/listening/:id" => "songs#listening"
	get "/listenin/:id" => "songs#listenin"
	get "/pop/:id" => "songs#pop"
  end
   
end

  resources :comments
  resources :moods

  resources :playlists
  resources :raters do
collection do
get "/signup" => "raters#signup"
get "/up/:id" => "raters#up"
get "/upp/:id" => "raters#upp"
get "/uppp/:id" => "raters#uppp"
end
end

  resources :populars

  resources :artists
  get "/search" => "songs#search", as: 'search'
  match '/lyrics', to: 'moods#lyrics', via: :get
match '/lyricsdetected', to: 'moods#lyricsdetected', via: :post
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users

end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :mood
  belongs_to :user
  has_many :songs
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
  before_action :set_playlist, only: [:show, :edit, :update, :destroy]

  respond_to :html

  def index
    @raters=Rater.where(:user_id => current_user.id, :play => 1)
    respond_with(@playlists,@raters)
  end

  def show

  popu=Rater.where("song_id IN (select song_id from populars order by count desc limit 10) and user_id=?",@playlist.user_id)
   

@moods=Mood.all
recom=Rater.where.not(:user_id => current_user.id)

recomuser=Rater.where("mood_id<>? and user_id=?",@playlist.mood,current_user.id)

recom2=recom.where(mood_id:  @playlist.mood)

set=recom2.where("song_id IN (select song_id from raters where mood_id=? and user_id=?)",@playlist.mood,current_user.id)

@f2=set.select("user_id,mood_id,song_id,count(*) as total_count").group(:user_id).order("total_count DESC").limit(3)
u1=@f2.offset(1).first
u2=@f2.offset(2).first
u3=@f2.offset(3).first
reccomending=recomuser.where("song_id IN (select song_id from raters where mood_id=? and user_id IN (?,?,?))", @playlist.mood,u1.user_id,u2.user_id,u3.user_id)


   raters=Rater.where(:mood_id=>@playlist.mood , :user_id => current_user.id)
   pop=raters.order(count: :desc,search: :desc).take(10)

@rec = pop | reccomending | popu
    respond_with(@playlist,@rater)
 
  end

  def new
    @playlist = Playlist.new
    
    respond_with(@playlist)
  end

  def edit
  end

  def create
    @playlist = Playlist.new(playlist_params)
    @playlist.save
    respond_with(@playlist)
  end

  def update
    @playlist.update(playlist_params)
    respond_with(@playlist)
  end

  def destroy
    @playlist.destroy
    respond_with(@playlist)
  end

  private
    def set_playlist
      @playlist = Playlist.find(params[:id])
    end

     def playlist_params
statement = params[:playlist][:name]
    	
	`python rosh.py #{statement}`

	file = File.open("finish.txt", 'rb')                           #execute python code here and get the value into finish.txt
	while !file.eof?
		line = file.readline
		line=line.gsub(/\n/," ")
	end

	params = ActionController::Parameters.new({
playlist: {
name: statement, 
mood_id: line,
user_id: current_user.id
}
})
params.require(:playlist).permit(:name, :mood_id, :user_id)
	end
	end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/views/playlists/_form.html.erb
<%= simple_form_for(@playlist) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    How do you feel today?
    <%= f.input :name , :label => false%>
  
  	
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/playlists/edit.html.erb
<h1>Editing Playlist</h1>

<%= render 'form' %>

<%= link_to 'Show', @playlist %> |
<%= link_to 'Back', playlists_path %>

app/views/playlists/index.html.erb
<p id="notice"><%= notice %></p>


<h1>Listing Playlists</h1>
<p> Click here to download the MP3 Player for Offline Purposes! :) </p>
<a href="<%= image_path("OfflinePurpleBlues.zip")%>" download>Offline Purple Blues</a>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Mood</th>
      <th>User</th>
	<th>ID</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
<% @playlist=Playlist.where(user_id: current_user.id); %>
    <% @playlist.each do |playlist| %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.mood.moodname if playlist.mood%></td>
        <td><%= playlist.user.name if playlist.user%></td>
<td><%= playlist.id %></td>
        <td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>




<table class="sortable" id="t01" border=2 style="width:100%">

<br><br>

  <thead>
    <tr>
      <th>Name</th>
      <th>Mood</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>

   <% @raters.each do |ra| %>

      <tr>
        <td><%= ra.song.name %></td>
        <td><%= ra.mood.moodname %></td>
        <td><%= link_to 'Play', ra %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Playlist', new_playlist_path %>

app/views/playlists/index1.html.erb
 <!DOCTYPE html>

<html lang="en">
<head>

<!-- add styles and scripts -->
	<%=stylesheet_link_tag 'css/styles.css' %>
	<%=stylesheet_link_tag 'me.css' %>
	<%=javascript_include_tag 'js/jquery-1.7.2.min.js' ,'js/jquery-ui-1.8.21.custom.min.js','js/man.js' %>
<script>
function myFunction(id) {
    if (document.getElementById(id).style.display == "none") {
    document.getElementById(id).style.display = 'table';
  }

  else {
    document.getElementById(id).style.display = "none";
  }
}

function Yay() {
    alert("Glad you loved the song.");
   
}

function Boo() {
 alert("This song wont be played again.");  
}


</script>
    
</head>
<body>
    <div class="example">

        <div class="player">
            <div class="pl"></div>
            <div class="title"></div>

	    <div class="mood"></div>
            <div class="cover"></div>
            <div class="controls">
                <div class="play"></div>
                <div class="pause"></div>
                <div class="rew"></div>
                <div class="fwd"></div>
            </div>
            <div class="volume"></div>
            <div class="tracker"></div>
        </div>

        <ul class="playlist">
	<% @playlists.each do |pl|%>
            <li audiourl="<%=pl.song.audio.url%>" mood="<%=pl.mood.moodname%>" songid="<%=pl.song.id%>"><%=pl.song.name%> </li>
	  <% end %>        



	</ul>

    </div>
</body>

<a href="#" onclick="myFunction('t01'); return false;">View/Hide Download Table</a>

<table id="t01" border=2 style="width:100%">
<h1> DOWNLOAD SONGS! </h1>
<p> You can right click on the download link to download files, if the file does not get downloaded. </p>
<br><br>

  <thead>
    <tr>
      <th>Name</th>
      <th>Mood</th>
      <th>Artist</th>
      <th colspan="1"></th>
    </tr>
  </thead>

  <tbody>

    <% @playlists.each do |pl| %>
      <tr>
        <td><%= pl.song.name %></td>
        <td><%= pl.mood.moodname %></td>
        <td><%= pl.song.artist.artistname %> </td>
	<td><%= link_to 'Show', playlist %></td>
        <td><%= link_to 'Edit', edit_playlist_path(playlist) %></td>
        <td><%= link_to 'Destroy', playlist, method: :delete, data: { confirm: 'Are you sure?' } %></td>
	<td><%= link_to 'Download' ,pl.song.audio.url(:original, false) %> </td>
      </tr>
    <% end %>
  </tbody>
</table>
<br><br><br>
<a href="#" onclick="myFunction('t02'); return false;">View/Hide Rate Table</a>
<br><br>
<h1> RATE SONGS! </h1>
<p> 1st star => perfect. 2nd star => change mood. 3rd Star => Wrong mood wrong song!</p>

<br><br><br>

<table id="t02" border=2 style="width:100%">

  <thead>
    <tr>
      <th>Name</th>
      <th>Mood</th>
      <th>Artist</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>

    <% @playlists.each do |playlist| %>

<% @rater=Rater.where("song_id=? and user_id=?", pl.song.id,current_user.id).take %>
      <tr>
        <td><%= playlist.name %></td>
        <td><%= playlist.mood.moodname %></td>
        <td><%= playlist.song.artist.artistname %></td>
	<td><a class="rating" onclick=Yay()><span>★★★</span></a></td>
	<td><%= link_to '★★' ,edit_rater_path(@rater)%></td>
	<td><a class="rating" href="javascript:return true" onclick=Boo()><span>★</span></a> </td>


      </tr>

    <% end %>
  </tbody>
</table>
<br><br><br>

<%= link_to 'New Playlist', new_playlist_path %>


</html>

app/views/playlists/new.html.erb
<h1>New Playlist</h1>

<%= render 'form' %>



<%= link_to 'Back', playlists_path %>

app/views/playlists/show.html.erb
<head>
    <!-- add styles and scripts -->
  <%=stylesheet_link_tag 'css/styles.css' %>

	<%=stylesheet_link_tag 'stars.css' %>
	<%=stylesheet_link_tag 'me.css' %>
	<%=javascript_include_tag 'js/jquery-1.7.2.min.js' ,'js/jquery-ui-1.8.21.custom.min.js','js/man.js' %>
	<%=javascript_include_tag 'sorttable.js'%>

</head>

<script>
function Rateme(number)
{
$.ajax('/raters/up/'+number,{type: 'GET'});
}
function Rateme1(number)
{
$.ajax('/raters/upp/'+number,{type: 'GET'});
}
function Rateme2(number)
{
$.ajax('/raters/uppp/'+number,{type: 'GET'});
}
</script>
<h1> PLAYLIST DETAILS</h1>
<p id="notice"><%= notice %></p>
<div class="blockblack1">
  <p>
    <strong>Name:</strong>
    <%= @playlist.name.titleize %>
  </p>

  <p>
    <strong>Mood:</strong>
    <%= @playlist.mood.moodname.titleize %>
  </p>

  <p>
    <strong>User:</strong>
    <%= @playlist.user.email.titleize %>
  </p>

</div>
<br><h1> GENERATED PLAYLIST</h1>

<div class="blockblack">
    <div class="example">
        <div class="player">
            <div class="pl"></div>
            <div class="title"></div>
            <div class="artist"></div>
	    <div class="mood"></div>
            <div class="cover"></div>
            <div class="controls">
                <div class="play"></div>
                <div class="pause"></div>
                <div class="rew"></div>
                <div class="fwd"></div>
            </div>
            <div class="volume"></div>
            <div class="tracker"></div>
        </div>

 
        <ul class="playlist">

	  <% @rec.each do |ra|%>
            <li audiourl="<%=ra.song.audio.url%>" artist="<%=ra.song.artist.artistname%>" mood="<%=ra.mood.moodname%>" songid="<%=ra.id%>"  ><%=ra.song.name%> </li>
	  <% end %>        
	</ul>

    </div>

<%= link_to '★' ,raters_path%> 
<h1>Listing Songs generated in PLAYLIST</h1>
<table class="table table-hover">
 <thead>
    <tr>
      <th>Name</th>
      <th>Mood</th>
      <th>Artist</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
<%i=0%>
   <% @rec.each do |ra| %>
<%i=i+1%>
      <tr>
        <td><%= ra.song.name %></td>
        <td><%= ra.mood.moodname %></td>
        <td><%= ra.song.artist.artistname %></td>
        <td><a href="<%=ra.song.audio.url(:original, false)%>" download>Download</a></td>
 <td><span class="rating" id="<%= i %>">
        
        <input type="radio" onclick="Rateme2(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-3" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-3" class="rating-star"></label>
<%i=i+1%>       
 <input type="radio" onclick="Rateme(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-2" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-2" class="rating-star"></label>
<%i=i+1%>
        <input type="radio" onclick="Rateme1(<%=ra.song.id%>)" class="rating-input"
                id="rating-input-<%= i%>-1" name="rating-input-<%= i%>"/>
        <label for="rating-input-<%= i%>-1" class="rating-star"></label>

</span></td> 
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to 'Edit', edit_playlist_path(@playlist) %> |
<%= link_to 'Back', playlists_path %>
</div>