config/routes.rb
Rails.application.routes.draw do
  resources :comments

  resources :playlists

resources :songs do
 
  collection do
   	get 'listofsong'
	get "/listening/:id" => "songs#listening"
	get "/listenin/:id" => "songs#listenin"
	get "/pop/:id" => "songs#pop"
  end
   
end

  resources :comments
  resources :moods

  resources :playlists
  resources :raters do
collection do
get "/signup" => "raters#signup"
get "/up/:id" => "raters#up"
get "/upp/:id" => "raters#upp"
get "/uppp/:id" => "raters#uppp"
end
end

  resources :populars

  resources :artists
  get "/search" => "songs#search", as: 'search'
  match '/lyrics', to: 'moods#lyrics', via: :get
match '/lyricsdetected', to: 'moods#lyricsdetected', via: :post
  mount Upmin::Engine => '/admin'
  root to: 'visitors#index'
  devise_for :users
  resources :users

end

app/models/artist.rb
class Artist < ActiveRecord::Base
belongs_to :song
end

app/models/comment.rb
class Comment < ActiveRecord::Base
end

app/models/mood.rb
class Mood < ActiveRecord::Base
belongs_to :song
has_many :rater
end

app/models/playlist.rb
class Playlist < ActiveRecord::Base
  belongs_to :mood
  belongs_to :user
  has_many :songs
end

app/models/popular.rb
class Popular < ActiveRecord::Base
  belongs_to :song
end

app/models/rater.rb
class Rater < ActiveRecord::Base
  belongs_to :user
  belongs_to :song
  belongs_to :mood
validates_uniqueness_of :user_id, scope: :song_id
end

app/models/reccommender.rb
class Reccommender < ActiveRecord::Base
  belongs_to :rater
	validates_uniqueness_of :user_id
end

app/models/song.rb
class Song < ActiveRecord::Base
  belongs_to :mood
  belongs_to :artist
has_attached_file :audio                   
validates_attachment_presence :audio
validates_attachment_content_type :audio, :content_type => [ 'audio/mp3','audio/mpeg']
end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
  	if User.count == 1
    	self.role ||= :admin
    else
    	self.role ||= :user
    end
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/helpers/artist_helper.rb
module ArtistHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/mood_helper.rb
module MoodHelper
end

app/helpers/moods_helper.rb
module MoodsHelper
end

app/helpers/playlist_helper.rb
module PlaylistHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/popular_helper.rb
module PopularHelper
end

app/helpers/rater_helper.rb
module RaterHelper
end

app/helpers/song_helper.rb
module SongHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<div class="navbar-wrapper ">
      <div class="container">


<div class="navbar navbar-inverse navbar-fixed-top animated fadeInDown" role="navigation" id="top-nav">
          <div class="container">
            <div class="navbar-header">
              <!-- Logo Starts -->
              <%= link_to "Home",root_path, :class=> "navbar-brand" %>
              <!-- #Logo Ends -->


              <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
              </button>

            </div>


            <!-- Nav Starts -->
            <div class="navbar-collapse  collapse">
              <ul class="nav navbar-nav navbar-right" >
                   <%= render 'layouts/navigation_links' %>
                   

                  
                 <!-- <li><a href="#about">About</a></li>
                 <li><a href="#playlist">Playlist</a></li>
                 <li><a href="#album">Albums</a></li>
                 <li><a href="#blogevent">Events & Blog</a></li>
                 <li><a href="#contact">Contact</a></li> -->
              </ul>
            </div>
            <!-- #Nav Ends -->

          </div>
        </div>

      </div>
    </div>
        </div>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

   
<script>
function Rateme2()
{
$.ajax('/raters/signup',{type: 'GET'});
}
</script>

 

<% if user_signed_in? %>  
<li><%= link_to '★', '#',:onclick =>'Rateme2()'%> </li>

  		<li><%= link_to 'Edit account', edit_user_registration_path %></li>
  		<li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
  		<li><%= link_to 'Playlist', playlists_path  %></li>
  		<li><%= link_to 'Songs', listofsong_songs_path %></li>            
<% else %>
                 <li><a href="#about">About</a></li>
 		 <li><a href="#playlist">Playlist</a></li>
                 <li><a href="#album">Albums</a></li>
                 <li><a href="#blogevent">Events & Blog</a></li>
                  <li><%= link_to 'Sign in', new_user_session_path %></li>
  		<li><%= link_to 'Sign up', new_user_registration_path %></li>
		<li><a href="#contact">Contact</a></li> 
<% end %>
<% if user_signed_in? %>
  <% if current_user.admin? %>
    <li><%= link_to 'Admin', '/admin' %></li>
    <li><%= link_to 'Users', users_path %></li>
<li><%= link_to 'Songs', songs_path %></li>
  <% end %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
<%= javascript_include_tag 'applicationa', 'data-turbolinks-track' => true  %>
<%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
<%= javascript_include_tag 'page.js' %>
<%= csrf_meta_tags %>
<title>Heart Beats</title>
<meta charset="UTF-8" />



</head>
<body>



<!-- Header Starts -->
<div class="navbar-wrapper ">
	<div class="container">

		<%= render 'layouts/navigation' %>


	</div>
</div>
<!-- #Header Starts -->







<!-- overlay -->
<div class="container overlay">
<br>
<br>
<br>
	

<!-- set a purple bg for all pages except home and sign in sign up pages -->

	<div class="<%= 'blockblack' if !((params[:action]=='index' and params[:controller]=='visitors') or (params[:controller]=='devise/registrations') or (params[:controller]=='devise/sessions') or (params[:controller]=='playlists' and params[:action]=='show')) %>">
	<!-- home banner starts -->
		<%= yield %>
	<!-- home banner ends -->
	</div>


	<!-- blockblack -->
	
	<!-- blockblack -->

</div>
<!-- overlay -->



<!-- Footer Starts -->
<!-- <div id="footer">
	<div class="container">
		Copyright 2014 DJ KRANKS.
	</div>
</div> -->
<!-- # Footer Ends -->


<!-- background slider -->
<div id="myCarousel" class="carousel slide hidden-xs">
	<div class="carousel-inner">
		<div class="active item"><%=image_tag('back1.jpg') %></div>
		<div class="item"><%=image_tag('back2.jpg') %></div>
		<div class="item"><%=image_tag('back3.jpg') %></div>
	</div>
</div>
<!-- background slider -->






<!-- Modal -->
<div class="modal fade" id="blogdetail" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">
			<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>


			<div id="blog">
				<h2>New trends in music</h2>
				<small>Posted on: Jan 20, 2013</small>

				<a href="#" class="thumbnail"><%=image_tag(('1.jpg') , :class => "img-responsive", :alt=>"blog") %></a>

				<div class="col-lg-8 col-lg-offset-2">                                                                           
					<p>You give the feels, we make the feels ;) </p>
					<p>Ash, Rosh, and AK present to you, the MUSIC RECOMMENDATION SYSTEM! :D </p>
					<p>I DON'T KNOW WHAT TO TYPE HERE!!!!!</p>
				</div>


			</div>


		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->









<!-- Modal -->
<div class="modal fade" id="albumdetail" tabindex="-1" role="dialog">
	<div class="modal-dialog">
		<div class="modal-content">



			<h2>Crazy Frescos</h2>
			<iframe width="100%" height="450" scrolling="no" frameborder="no" src="https://w.soundcloud.com/player/?url=https%3A//api.soundcloud.com/playlists/24314082&amp;theme_color=000000&amp;color=ff5500&amp;auto_play=false&amp;hide_related=false&amp;show_artwork=false"></iframe>


		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->



<!-- // <script src="http://code.jquery.com/jquery-1.7.1.min.js" type="text/javascript" ></script> -->
<!-- boostrap -->

</body>
</html>